name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: flake8 app/

      - name: Run Unit Tests
        run: pytest app/tests

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}"

  build-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

      - name: Update Helm Values
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/" k8s/helm-chart/values.yaml

      - name: Commit Image Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag"
          git push